FROM golang:1.18.1

RUN mkdir /go/src/backend

WORKDIR /go/src/backend

COPY . ./

RUN go mod download

# RUN apt-get update
# RUN apt-get -y install mysql-client

RUN go install github.com/cosmtrek/air@latest

EXPOSE 8080

# CMD [ "go", "run", "main.go" ]
CMD [ "air" ]
