FROM golang:1.18.1

RUN mkdir /go/src/backend

WORKDIR /go/src/backend

COPY . ./

RUN go mod download

# RUN go install github.com/cosmtrek/air@v1.29.0

EXPOSE 8080

CMD [ "go", "run", "main.go" ]
# CMD [ "air", "-c", ".air.toml" ]
